layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  facebook: pravallika.reddy.756412
  hackerrank: Pravali_07
  instagram: prvli_07
  linkedin: p-pravallika
  telegram: Pravalireddy
  twitter: PravallikaPuli3

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
    description: Problem solving and competitive programming in Python.

  - name: Flask
    web_url: https://github.com/topics/flask
    image_url: https://icon2.cleanpng.com/20180508/rie/kisspng-flask-python-web-framework-web-application-tutoria-5af1dbb6d4ea62.8503418315257998628721.jpg
    description: Web development using Flask Framework.

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png
    description: Building interactive web applications.

schools:
  - name: JNTUA College of Engineering, Pulivendula(2017-2021)
    web_url: https://jntuacep.ac.in/
    image_url: https://jntuacep.ac.in/results/images/clglogo.jpg
    description: Undergraduate in Computer Science and Engineering. CGPA 8.55/10

  - name: Sri Chaitanya Junior College, Tirupati (2015-2017)
    web_url: https://srichaitanya.net/
    image_url: https://images.jdmagicbox.com/comp/vijayawada/q4/0866px866.x866.170924235250.x7q4/catalogue/sri-chaitanya-junior-college-tadigaddapa-vijayawada-colleges-1mgitpqd0y.jpg?clr=#54121d
    description: Stream - Mathematics, Physics and Chemistry. Percentage 97.3/100
